# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provision :shell, :path => "provision.sh"
  config.ssh.forward_agent = true

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.define :node1 do |node|
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.network :private_network, ip:"192.168.33.11"
  end

  config.vm.define :node2 do |node|
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.network :private_network, ip:"192.168.33.12"
  end
end
