sudo: required
dist: trusty
language: generic
cache:
    apt: true
    directories:
        - "$HOME/.stack/"
        - "$HOME/.local/bin/"
        - ".stack-work/"
os:
    - linux
before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - sudo apt-get purge -y google-chrome-stable
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - curl -sL https://raw.githubusercontent.com/falgon/SrookCppLibraries/8e7e30275e407ab6d67bddebf898c826b61fa553/travis/linux/before_install.sh | bash
    - wget --no-check-certificate https://raw.githubusercontent.com/falgon/SrookCppLibraries/a3b43fe51ed3cc17e9683fdedee27d59517a128e/travis/linux/install.sh 
    - sed -i -e '10,12d' install.sh
    - chmod +x install.sh
    - ./install.sh
    - sudo apt-get -qq -y -f --no-show-upgraded install libc6-dev libc6-dev-i386 libffi-dev libgmp-dev xz-utils libpcap-dev
install:
    - stack --no-terminal test --only-dependencies
jobs:
    include:
        - stage: Run build
          script: stack build --fast
        - stage: Run Hlint
          script: curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .

notifications:
    email: false
